### ISSUE TITLE
Para os interessados neste miniprojeto

### ISSUE THREAD

**Issue by dssgPT** [dssg-pt/mp-mapeamento-cp7#1]
Se estás interessado em contribuir para este Mini-Projecto e possuis todas as características que fazem de ti O VOLUNTÁRIO, deixa um comentário abaixo com a tua visão sobre a eterna questão: Quem nasceu primeiro? O ovo ou a galinha? 🐣

A selecção será feita **com base na ordem de manifestação de entusiasmo**, assumindo que o candidato possui as skills técnicas indispensáveis. Quaisquer divagações filosóficas serão grandemente apreciadas... 👇

**Comment by J-Rodrigues0** [comment]
Como está aqui: 🐣, a galinha sai do ovo, logo, o ovo nasceu primeiro!

Gostaria muito de aplicar as minhas skills de Python e Data Science para ajudar neste projeto! Obrigado pela oportunidade!

**Comment by dssgPT** [comment]
Olá @J-Rodrigues0!

Muito obrigado por partilhares connosco a tua visão da eterna questão. Ainda mais com base nos recursos apresentados! Bravo! :smiley:

Obrigado também pelo interesse que demonstraste neste projeto. Como sempre, sentimo-nos honrados e queremos parabenizer-te por decidires embarcar nesta viagem connosco.

Aproveitamos para pedir-te para entrares em contacto connosco através do e-mail volunteers@dssg.pt, para que possamos marcar a reunião de kick-off do projeto.

**Comment by ernesto-teixeira-silva** [comment]
Olá pessoal, 

Para mim a galinha nasceu primeiro, pois para haver ovo teve que haver quem o gerou🐔 . Não me parece que o Criador tenha criado o Adão a Eva e um ovo 😄 

Já me deparei várias vezes com a necessidade desta informação (Não sobre a resposta a quem nasceu primeiro? O ovo ou a galinha). 😄 

Nada como, em equipa, virmos a fazer o mapeamento entre código postal e freguesia, concelho, e distrito.

Também gostava de associar-me a este projeto colocando em prática as minhas skills em Data Science e aprofundando-as 📭 

Bem haja à @dssgPT pelo excelente trabalho em prol da comunidade

Saúde!
